//@version=2
study(title="ScannerData", shorttitle="_SD_")


// study(title="Average True Range", shorttitle="ATR", overlay=false)
plot(rma(tr(true), 14), title="ATR")


// study("Average Directional Index", shorttitle="ADX")
dirmov(len) =>
	up = change(high)
	down = -change(low)
	truerange = rma(tr, len)
	plus = fixnan(100 * rma(up > down and up > 0 ? up : 0, len) / truerange)
	minus = fixnan(100 * rma(down > up and down > 0 ? down : 0, len) / truerange)
	[plus, minus]

adx(dilen, adxlen) => 
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)

plot(adx(14, 14), title="ADX")


// study(shorttitle="BB", title="Bollinger Bands", overlay=true)
lengthBB = 20
srcBB = close
multBB = 2
basisBB = sma(srcBB, lengthBB)
devBB = multBB * stdev(srcBB, lengthBB)
upperBB = basisBB + devBB
lowerBB = basisBB - devBB
plot(basisBB, title="BB.basis")
plot(upperBB, title="BB.upper")
plot(lowerBB, title="BB.lower")


// study(title="Moving Average Convergence/Divergence", shorttitle="MACD")
sourceMACD = close
fastLengthMACD = 12
slowLengthMACD = 26
signalLengthMACD = 9
fastMAMACD = ema(sourceMACD, fastLengthMACD)
slowMAMACD = ema(sourceMACD, slowLengthMACD)
macdMACD = fastMAMACD - slowMAMACD
signalMACD = sma(macdMACD, signalLengthMACD)
histMACD = macdMACD - signalMACD
plot(histMACD, title="MACD.hist")
plot(macdMACD, title="MACD.macd")
plot(signalMACD, title="MACD.signal")


//study(title="Momentum", shorttitle="Mom")
plot(close - close[10], title="Mom")


//study(title="Relative Strength Index", shorttitle="RSI")
plot(rsi(close,14), title="RSI")
plot(rsi(close,7), title="RSI7")


// study(title="Moving Average", shorttitle="MA", overlay=true)
plot(sma(close, 10), title="SMA10")
plot(sma(close, 20), title="SMA20")
plot(sma(close, 30), title="SMA30")
plot(sma(close, 50), title="SMA50")
plot(sma(close, 100), title="SMA100")
plot(sma(close, 200), title="SMA200")

// study(title="Exponential Moving Average", shorttitle="EMA", overlay=true)
plot(ema(close, 10), title="EMA10")
plot(ema(close, 20), title="EMA20")
plot(ema(close, 30), title="EMA30")
plot(ema(close, 50), title="EMA50")
plot(ema(close, 100), title="EMA100")
plot(ema(close, 200), title="EMA200")

// study(title="Stochastic", shorttitle="Stoch")
lengthStoch = 14
smoothKStoch = 1
smoothDStoch = 3
kStoch = sma(stoch(close, high, low, lengthStoch), smoothKStoch)
dStoch = sma(kStoch, smoothDStoch)
plot(kStoch, title="Stoch.K")
plot(dStoch, title="Stoch.D")

// performance
rateOfreturn(v1, v2) => (v1 - v2) * 100 / v2
rr(bb) =>
    rof = rateOfreturn(close, close[bb])
    rof[1]
plot(rr(5), title="Perf.W")
plot(rr(21), title="Perf.1M")
plot(rr(63), title="Perf.3M")
plot(rr(126), title="Perf.6M")
plot(rr(252), title="Perf.Y")
lastYearClose = lastYearClose[1]
if year > year[1]
    lastYearClose := close[1]
plot(rateOfreturn(close, lastYearClose)[1], title="Perf.YTD")

// volatility
volatility(bb) => sma((high-low)/low * 100, bb)
plot(volatility(5), title="Volatility.W")
plot(volatility(21), title="Volatility.M")
plot(tr(true)*100/low, title="Volatility.D")

// average volume
plot(sma(volume,90*5/7)[1], title="average_volume")

// high & low
allTimeHigh = max(nz(allTimeHigh[1], high), high)
allTimeLow = min(nz(allTimeLow[1], low), low)
plot(allTimeHigh, title="High.All")
plot(allTimeLow, title="Low.All")
plot(nz(highest(high, 52*5), allTimeHigh), title="price_52_week_high")
plot(nz(lowest(low, 52*5), allTimeLow), title="price_52_week_low")
plot(nz(highest(high, 126), allTimeHigh), title="High.6M")
plot(nz(lowest(low, 126), allTimeLow), title="Low.6M")
plot(nz(highest(high, 63), allTimeHigh), title="High.3M")
plot(nz(lowest(low, 63), allTimeLow), title="Low.3M")
plot(nz(highest(high, 21), allTimeHigh), title="High.1M")
plot(nz(lowest(low, 21), allTimeLow), title="Low.1M")

// Commodity Channel Index
plot(cci(close, 20), title = "CCI20")

// Donchian Channels
donchLen = 20
donchUpper = highest(donchLen)
donchLower = lowest(donchLen)
plot(donchLower, title = "DonchCh20.Lower")
plot(donchUpper, title = "DonchCh20.Upper")
plot(avg(donchUpper, donchLower), title="DonchCh20.Middle")

// Hull Moving Average
hullMALength = 9
hullMA_n2ma=2*wma(close,round(hullMALength/2))
hullMA_nma=wma(close,hullMALength)
plot(wma(hullMA_n2ma - hullMA_nma, round(sqrt(hullMALength))), title = "HullMA9")

// Awesome Oscillator
plot(sma(hl2, 5) - sma(hl2, 34), title = "AO")

// Pivot Points
pivotM_open = nz(pivotM_open[1],open)
pivotM_high = nz(pivotM_high[1],high)
pivotM_low = nz(pivotM_low[1],low)

pivotM_prev_open = nz(pivotM_prev_open[1])
pivotM_prev_high = nz(pivotM_prev_high[1])
pivotM_prev_low = nz(pivotM_prev_low[1])
pivotM_prev_close = nz(pivotM_prev_close[1])

pivotM_Month = month(time)
if pivotM_Month != pivotM_Month[1]
    pivotM_prev_open := pivotM_open
    pivotM_prev_close := close[1]
    pivotM_prev_high := pivotM_high
    pivotM_prev_low := pivotM_low

    pivotM_open := open
    pivotM_high := high
    pivotM_low := low
else
    pivotM_high := max(pivotM_high, high)
    pivotM_low := min(pivotM_low, low)

// Classic
pivotM_Median = (pivotM_prev_high + pivotM_prev_low + pivotM_prev_close)/3
plot(pivotM_Median, title = 'Pivot.M.Classic.Middle')
plot(pivotM_Median * 2 - pivotM_prev_low, title = 'Pivot.M.Classic.R1')
plot(pivotM_Median * 2 - pivotM_prev_high, title = 'Pivot.M.Classic.S1')
plot(pivotM_Median + 1*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Classic.R2')
plot(pivotM_Median - 1*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Classic.S2')
plot(pivotM_Median + 2*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Classic.R3')
plot(pivotM_Median - 2*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Classic.S3')

// Fibonacci
plot(pivotM_Median, title = 'Pivot.M.Fibonacci.Middle')
plot(pivotM_Median + 0.382 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.R1')
plot(pivotM_Median - 0.382 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.S1')
plot(pivotM_Median + 0.618 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.R2')
plot(pivotM_Median - 0.618 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.S2')
plot(pivotM_Median + 1 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.R3')
plot(pivotM_Median - 1 * (pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Fibonacci.S3')

// Woodie
pivotM_Woodie_Median = (pivotM_prev_high + pivotM_prev_low + pivotM_prev_open * 2)/4
plot(pivotM_Woodie_Median, title = 'Pivot.M.Woodie.Middle')
plot(pivotM_Woodie_Median * 2 - pivotM_prev_low, title = 'Pivot.M.Woodie.R1')
plot(pivotM_Woodie_Median * 2 - pivotM_prev_high, title = 'Pivot.M.Woodie.S1')
plot(pivotM_Woodie_Median + 1*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Woodie.R2')
plot(pivotM_Woodie_Median - 1*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Woodie.S2')
plot(pivotM_prev_high + 2*(pivotM_Woodie_Median - pivotM_prev_low), title = 'Pivot.M.Woodie.R3')
plot(pivotM_prev_low - 2*(pivotM_prev_high - pivotM_Woodie_Median), title = 'Pivot.M.Woodie.S3')

// Demark
pivotM_Demark_X = pivotM_prev_high + pivotM_prev_low*2 + pivotM_prev_close
if pivotM_prev_close == pivotM_prev_open
    pivotM_Demark_X := pivotM_prev_high + pivotM_prev_low + pivotM_prev_close*2
if pivotM_prev_close > pivotM_prev_open
    pivotM_Demark_X := pivotM_prev_high*2 + pivotM_prev_low + pivotM_prev_close
plot(pivotM_Demark_X/4, title = 'Pivot.M.Demark.Middle')
plot(pivotM_Demark_X/2 - pivotM_prev_low, title = 'Pivot.M.Demark.R1')
plot(pivotM_Demark_X/2 - pivotM_prev_high, title = 'Pivot.M.Demark.S1')

// Camarilla
plot(pivotM_Median, title = 'Pivot.M.Camarilla.Middle')
plot(pivotM_prev_close + 1.1/12.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.R1')
plot(pivotM_prev_close - 1.1/12.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.S1')
plot(pivotM_prev_close + 1.1/6.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.R2')
plot(pivotM_prev_close - 1.1/6.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.S2')
plot(pivotM_prev_close + 1.1/4.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.R3')
plot(pivotM_prev_close - 1.1/4.0*(pivotM_prev_high - pivotM_prev_low), title = 'Pivot.M.Camarilla.S3')