//@version=4
study(title="ScannerData1", shorttitle="_SD1_")

// study(title="Average True Range", shorttitle="ATR", overlay=false)
plot(rma(tr(true), 14), title="ATR")


// study("Average Directional Index", shorttitle="ADX")
dirmov(len) =>
	up = change(high)
	down = -change(low)
	truerange = rma(tr, len)
	plus = fixnan(100 * rma(up > down and up > 0 ? up : 0, len) / truerange)
	minus = fixnan(100 * rma(down > up and down > 0 ? down : 0, len) / truerange)
	[plus, minus]

adx(dilen, adxlen) =>
	[plus, minus] = dirmov(dilen)
	sum = plus + minus
	adx = 100 * rma(abs(plus - minus) / (sum == 0 ? 1 : sum), adxlen)
	[adx, plus, minus]

[adxValue, adxPlus, adxMinus] = adx(14, 14)
plot(adxValue, title="ADX")
plot(adxPlus, title="ADX+DI")
plot(adxMinus, title="ADX-DI")
plot(adxPlus[1], title="ADX+DI[1]")
plot(adxMinus[1], title="ADX-DI[1]")
